name: Validate links

on:
  pull_request: null
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2.2.0
        continue-on-error: true  # Permite que o workflow continue mesmo se encontrar links quebrados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create issue
        if: steps.lychee.outcome != 'success'  # Verifica o resultado do passo do Lychee
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link checker report
          labels: 'report, automated-issue'
          content-filepath: ./lychee/out.md
      - name: Assign issues and pull requests
        if: steps.lychee.conclusion != 'success'
        uses: gustavofreze/auto-assign@1.1.4
        with:
          assignees: 'your-github-username'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          allow_self_assign: 'true'
          allow_no_assignees: 'true'
          assignment_options: 'ISSUE'